import {env} from 'cloudflare:workers';
const credentials=()=>{const e=env as unknown as Record<string,string>;return {key:e.AI_API_KEY,base:e.AI_BASE_URL,model:e.AI_MODEL};};
export async function GET(){const c=credentials();return Response.json({configured:Boolean(c.key&&c.base&&c.model)});}
const IDs=['front','back','leftSleeve','rightSleeve','collar'];
export async function POST(request:Request){
 const c=credentials();if(!c.key||!c.base||!c.model)return Response.json({error:'Connect an AI provider to use AI vision and natural-language editing. Local conversion and quick commands remain available.'},{status:503});
 try{if(!/^https:\/\//.test(c.base))throw new Error('The AI provider endpoint must use HTTPS.');const raw=await request.text();if(raw.length>2000000)return Response.json({error:'The image is too large for AI analysis.'},{status:413});const input=JSON.parse(raw);if(!['detect','customize'].includes(input.action))throw new Error('Unsupported AI action.');
 const detect=input.action==='detect';if(detect&&(!input.image||!/^data:image\/(jpeg|png);base64,[A-Za-z0-9+/=]+$/.test(input.image)))throw new Error('Provide a valid image.');if(!detect&&(typeof input.command!=='string'||input.command.length>500))throw new Error('Provide a design request of 500 characters or fewer.');
 const system=detect?'You identify visible jersey artwork regions for photo rectification. Return JSON only: {"quads":{"front":[{"x":0.1,"y":0.1},...],...},"message":"..."}. Each quad is four clockwise points, top-left, top-right, bottom-right, bottom-left, normalized 0..1. Available panel keys: front, back, leftSleeve, rightSleeve, collar. Only include visible panels; do not invent an unseen back. Select central body artwork separately from sleeves and collar. For a flat production sheet select the entire bounding rectangle of each flat piece. Use the actual image.':'You edit a jersey production design. Return JSON only: {"primary":"#rrggbb", "secondary":"#rrggbb", "texts":[{"kind":"name|number|other","panel":"front|back|leftSleeve|rightSleeve|collar","text":"...","x":50,"y":25,"size":12}], "message":"..."}. All properties optional. Coordinates and size are percentages 0..100, size 3..80. Handle names, numbers, palette and text placement. Do not claim to generate imagery, erase original text, remove backgrounds or reconstruct artwork. If the request needs these unavailable operations, return only a message explaining it. Do not include instructions, HTML, SVG or scripts.';
 const content=detect?[{type:'text',text:`Layout: ${String(input.layout).slice(0,20)}. Suggest panel corners for this image.`},{type:'image_url',image_url:{url:input.image}}]:`Current primary: ${input.primary}; base: ${input.secondary}. Request: ${input.command}`;
 const response=await fetch(c.base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Authorization':`Bearer ${c.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:c.model,messages:[{role:'system',content:system},{role:'user',content}],temperature:.15,max_tokens:1500,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(45000)});
 if(!response.ok)return Response.json({error:'The AI provider could not complete this request. Check the model, vision support and account credit.'},{status:502});const result:any=await response.json();const text=result.choices?.[0]?.message?.content;if(typeof text!=='string')throw new Error('The AI provider returned no design result.');const output=JSON.parse(text.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));
 const safe:any={message:typeof output.message==='string'?output.message.slice(0,500):'AI suggestions are ready for review.'};for(const color of ['primary','secondary'])if(typeof output[color]==='string'&&/^#[0-9a-f]{6}$/i.test(output[color]))safe[color]=output[color];
 if(detect){safe.quads={};for(const id of IDs){const q=output.quads?.[id];if(Array.isArray(q)&&q.length===4&&q.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=1&&p.y>=0&&p.y<=1))safe.quads[id]=q.map(p=>({x:p.x,y:p.y}));}if(!Object.keys(safe.quads).length)throw new Error('No usable panel corners were found. Use the manual corner editor.');}
 else if(Array.isArray(output.texts))safe.texts=output.texts.slice(0,12).filter((t:any)=>IDs.includes(t.panel)&&typeof t.text==='string').map((t:any)=>({kind:['name','number','other'].includes(t.kind)?t.kind:'other',panel:t.panel,text:t.text.slice(0,80),x:Math.max(0,Math.min(100,Number(t.x)||50)),y:Math.max(0,Math.min(100,Number(t.y)||25)),size:Math.max(3,Math.min(80,Number(t.size)||12))}));
 return Response.json(safe);
 }catch(e){return Response.json({error:(e as Error).name==='TimeoutError'?'AI request timed out. You can keep editing locally.':(e as Error).message},{status:400});}
}
