import {traceOptions,stripTrace} from './trace-options';
export const PANEL_IDS = ['front', 'back', 'leftSleeve', 'rightSleeve', 'collar'] as const;
export type PanelId = typeof PANEL_IDS[number];
export type Point = {x:number;y:number};
export type Quad = [Point,Point,Point,Point];
export type Layout = 'pair'|'single'|'flat';
export type Panel = {id:PanelId;name:string;inner:string;width:number;height:number;cutPath:string;sourceWidth:number;sourceHeight:number;missing:boolean;paths:number;raster?:string;palette:string[]};
export type Overlay = {id:string;panel:PanelId;type:'text'|'logo';value:string;svg?:string;x:number;y:number;size:number;rotation:number;color:string;width?:number;height?:number};
export type Settings = {bodyWidth:number;bodyHeight:number;sleeveWidth:number;sleeveHeight:number;collarWidth:number;collarHeight:number;bleed:number;dpi:number;colors:number;detail:number;cleanup:'preserve'|'flat';removeBackground:boolean;showGuides:boolean};
export type Production = {panels:Panel[];overlays:Overlay[];settings:Settings;primary:string;secondary:string;name:string;source:string;sourceName:string;layout:Layout;quads:Record<PanelId,Quad>;reviewed:boolean;confirmed:boolean};
export const DEFAULT_SETTINGS:Settings={bodyWidth:560,bodyHeight:740,sleeveWidth:390,sleeveHeight:490,collarWidth:420,collarHeight:85,bleed:3,dpi:300,colors:16,detail:720,cleanup:'preserve',removeBackground:true,showGuides:true};
export const NAMES:Record<PanelId,string>={front:'Front body',back:'Back body',leftSleeve:'Left sleeve',rightSleeve:'Right sleeve',collar:'Collar'};
const q=(a:number,b:number,c:number,d:number,e:number,f:number,g:number,h:number):Quad=>[{x:a,y:b},{x:c,y:d},{x:e,y:f},{x:g,y:h}];
export function defaultQuads(layout:Layout):Record<PanelId,Quad>{
 if(layout==='flat')return {front:q(0,.092,.493,.092,.493,.568,0,.568),back:q(.505,.092,.997,.092,.997,.568,.505,.568),leftSleeve:q(.044,.571,.455,.571,.455,.954,.044,.954),rightSleeve:q(.548,.571,.959,.571,.959,.954,.548,.954),collar:q(.325,.003,.780,.003,.780,.078,.325,.078)};
 if(layout==='pair')return {front:q(.137,.194,.414,.188,.469,.870,.102,.850),back:q(.542,.173,.843,.167,.885,.927,.522,.902),leftSleeve:q(.09,.199,.172,.275,.106,.439,.009,.337),rightSleeve:q(.425,.197,.512,.283,.555,.377,.471,.458),collar:q(.212,.081,.364,.091,.359,.220,.218,.197)};
 return {front:q(.235,.160,.765,.160,.85,.940,.15,.940),back:q(.235,.160,.765,.160,.85,.94,.15,.94),leftSleeve:q(.035,.220,.245,.150,.250,.405,.060,.490),rightSleeve:q(.755,.150,.965,.220,.94,.490,.75,.405),collar:q(.370,.060,.630,.060,.64,.19,.36,.19)};
}
export function dimensions(id:PanelId,s:Settings){return id==='front'||id==='back'?{w:s.bodyWidth,h:s.bodyHeight}:id==='collar'?{w:s.collarWidth,h:s.collarHeight}:{w:s.sleeveWidth,h:s.sleeveHeight};}
export function patternPath(id:PanelId,w:number,h:number):string{
 const p=(x:number,y:number)=>`${(x*w).toFixed(2)} ${(y*h).toFixed(2)}`;
 if(id==='collar')return `M0 0H${w}V${h}H0Z`;
 if(id==='leftSleeve'||id==='rightSleeve')return `M${p(0,.19)} C${p(.17,.13)} ${p(.27,0)} ${p(.5,0)} C${p(.73,0)} ${p(.83,.13)} ${p(1,.19)} L${p(.79,1)} L${p(.21,1)}Z`;
 const neck=id==='front'?.13:.032;
 return `M${p(.055,.075)} L${p(.35,0)} Q${p(.5,neck)} ${p(.65,0)} L${p(.945,.075)} Q${p(.85,.32)} ${p(1,.36)} L${p(.977,1)} H${(w*.023).toFixed(2)} L${p(0,.36)} Q${p(.15,.32)} ${p(.055,.075)}Z`;
}
export async function loadImage(url:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('This file cannot be decoded. Try PNG, JPG, WebP, SVG, GIF, BMP or AVIF.'));im.src=url;});}
export async function readFile(file:File):Promise<string>{if(file.size>25*1024*1024)throw new Error('Choose an image smaller than 25 MB.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read that file.'));r.readAsDataURL(file);});}
export function canvas(w:number,h:number){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;}
export async function imageToData(url:string,max=1800){const im=await loadImage(url);const scale=Math.min(1,max/Math.max(im.width,im.height));const c=canvas(im.width*scale,im.height*scale);const ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(im,0,0,c.width,c.height);return {im,data:ctx.getImageData(0,0,c.width,c.height),canvas:c};}
function luminance(r:number,g:number,b:number){return .2126*r+.7152*g+.0722*b;}
export function estimatePalette(data:{width:number;height:number;data:Uint8ClampedArray}):string[]{
 const bins=new Map<string,{count:number;r:number;g:number;b:number}>();
 for(let i=0;i<data.data.length;i+=4*13){const [r,g,b,a]=data.data.slice(i,i+4);if(a<128)continue;const mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx-mn<30&&mx<190)continue;const key=`${r>>4},${g>>4},${b>>4}`;const v=bins.get(key)||{count:0,r:0,g:0,b:0};v.count++;v.r+=r;v.g+=g;v.b+=b;bins.set(key,v);}
 const sorted=[...bins.values()].sort((a,b)=>b.count-a.count);const colors:string[]=[];
 for(const a of sorted){const r=Math.round(a.r/a.count),g=Math.round(a.g/a.count),b=Math.round(a.b/a.count);const hex='#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join('');if(colors.every(c=>colorDistance(c,hex)>32))colors.push(hex);if(colors.length===6)break;}
 return colors.length?colors:['#750b2c','#f4eddb'];
}
function rgb(hex:string){return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];}
export function baseFillColour(data:{data:Uint8ClampedArray},primary:string,secondary:string){const p=rgb(primary),s=rgb(secondary);let dark=0,light=0;for(let i=0;i<data.data.length;i+=4*7){if(data.data[i+3]<128)continue;const c=[data.data[i],data.data[i+1],data.data[i+2]];const a=c.reduce((n,v,k)=>n+(v-p[k])**2,0),b=c.reduce((n,v,k)=>n+(v-s[k])**2,0);if(a<b)dark++;else light++;}return dark>light?primary:secondary;}
function colorDistance(a:string,b:string){const x=rgb(a),y=rgb(b);return Math.sqrt(x.reduce((n,v,i)=>n+(v-y[i])**2,0));}
export function chooseColors(palette:string[]){const ordered=palette.map(hex=>({hex,c:rgb(hex)}));const saturated=ordered.filter(({c})=>Math.max(...c)-Math.min(...c)>28&&luminance(...c as [number,number,number])<155);const primary=saturated[0];const light=ordered.filter(({c})=>Math.min(...c)<249).sort((a,b)=>luminance(...b.c as [number,number,number])-luminance(...a.c as [number,number,number]))[0];return {primary:primary?.hex||'#750b2c',secondary:light?.hex||'#f4eddb'};}
// Homography maps the four normalized source corners onto a rectified production panel.
export function homography(quad:Quad){
 const [p0,p1,p2,p3]=quad;const dx1=p1.x-p2.x,dx2=p3.x-p2.x,dx3=p0.x-p1.x+p2.x-p3.x;const dy1=p1.y-p2.y,dy2=p3.y-p2.y,dy3=p0.y-p1.y+p2.y-p3.y;const det=dx1*dy2-dx2*dy1;
 const g=Math.abs(det)<1e-12?0:(dx3*dy2-dx2*dy3)/det;const h=Math.abs(det)<1e-12?0:(dx1*dy3-dx3*dy1)/det;
 return {a:p1.x-p0.x+g*p1.x,b:p3.x-p0.x+h*p3.x,c:p0.x,d:p1.y-p0.y+g*p1.y,e:p3.y-p0.y+h*p3.y,f:p0.y,g,h};
}
export function validateQuad(quad:Quad){if(!Array.isArray(quad)||quad.length!==4||quad.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>1||p.y<0||p.y>1))throw new Error('All four panel corners must be inside the image.');const cross=quad.map((p,i)=>{const a=quad[(i+1)%4],b=quad[(i+2)%4];return (a.x-p.x)*(b.y-a.y)-(a.y-p.y)*(b.x-a.x);});if(cross.some(n=>n<=.00001)||Math.abs(quad.reduce((n,p,i)=>n+p.x*quad[(i+1)%4].y-p.y*quad[(i+1)%4].x,0))<.0001)throw new Error('Panel corners must form a non-crossing area in clockwise order.');}
export function warp(data:ImageData,quad:Quad,w:number,h:number):ImageData{
 validateQuad(quad);const out=new ImageData(w,h),m=homography(quad);const src=data.data,iw=data.width,ih=data.height;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=x/(w-1),v=y/(h-1),z=m.g*u+m.h*v+1;const sx=Math.min(iw-1,Math.max(0,(m.a*u+m.b*v+m.c)/z*(iw-1)));const sy=Math.min(ih-1,Math.max(0,(m.d*u+m.e*v+m.f)/z*(ih-1)));const x0=Math.floor(sx),y0=Math.floor(sy),x1=Math.min(iw-1,x0+1),y1=Math.min(ih-1,y0+1),tx=sx-x0,ty=sy-y0,idx=(y*w+x)*4;
 for(let k=0;k<4;k++)out.data[idx+k]=src[(y0*iw+x0)*4+k]*(1-tx)*(1-ty)+src[(y0*iw+x1)*4+k]*tx*(1-ty)+src[(y1*iw+x0)*4+k]*(1-tx)*ty+src[(y1*iw+x1)*4+k]*tx*ty;}
 return out;
}
// Flood only edge-connected white space; pale artwork inside the garment is retained.
export function removeOuterBackground(data:ImageData){const {width:w,height:h}=data,d=data.data;const visited=new Uint8Array(w*h),queue=new Int32Array(w*h);let head=0,tail=0;const isBg=(i:number)=>d[i*4+3]<20||(Math.min(d[i*4],d[i*4+1],d[i*4+2])>238&&Math.max(d[i*4],d[i*4+1],d[i*4+2])-Math.min(d[i*4],d[i*4+1],d[i*4+2])<18);const add=(i:number)=>{if(i<0||i>=w*h||visited[i]||!isBg(i))return;visited[i]=1;queue[tail++]=i;};
 for(let x=0;x<w;x++){add(x);add((h-1)*w+x);}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1);}while(head<tail){const i=queue[head++];d[i*4+3]=0;const x=i%w;if(x)add(i-1);if(x<w-1)add(i+1);if(i>=w)add(i-w);if(i<w*(h-1))add(i+w);}
 return data;
}
export function cleanupData(data:ImageData,primary:string,secondary:string,mode:'preserve'|'flat'){
 if(mode==='preserve')return data;const p=rgb(primary),s=rgb(secondary);const cut=(luminance(...p as [number,number,number])+luminance(...s as [number,number,number]))/2;
 for(let i=0;i<data.data.length;i+=4){if(!data.data[i+3])continue;const c=luminance(data.data[i],data.data[i+1],data.data[i+2])<cut?p:s;data.data[i]=c[0];data.data[i+1]=c[1];data.data[i+2]=c[2];}return data;
}
let traceWorker:Worker|undefined;
let workerFailed=false;
const pendingTraces=new Map<number,{resolve:(s:string)=>void;reject:(e:Error)=>void}>();let nextTrace=0;
export async function traceData(data:ImageData,colors=16,detail=true):Promise<string>{
 if(typeof Worker!=='undefined'&&!workerFailed){try{
 if(!traceWorker){traceWorker=new Worker(new URL('../workers/vectorizer.ts',import.meta.url),{type:'module'});traceWorker.onmessage=e=>{const job=pendingTraces.get(e.data.id);if(!job)return;pendingTraces.delete(e.data.id);if(e.data.error)job.reject(new Error(e.data.error));else job.resolve(e.data.inner);};traceWorker.onerror=()=>{workerFailed=true;for(const job of pendingTraces.values())job.reject(new Error('Worker unavailable'));pendingTraces.clear();traceWorker?.terminate();traceWorker=undefined;};}
 const id=++nextTrace,copy=new Uint8ClampedArray(data.data);return await new Promise<string>((resolve,reject)=>{pendingTraces.set(id,{resolve,reject});traceWorker!.postMessage({id,width:data.width,height:data.height,bytes:copy.buffer,colors,detail},[copy.buffer]);});
 }catch{workerFailed=true;}}
 const module=await import('imagetracerjs');return stripTrace(module.default.imagedataToSVG(data,traceOptions(colors,detail)));
}
export async function extractCutPath(data:ImageData){const mask=new ImageData(data.width,data.height);for(let j=0;j<data.data.length;j+=4){const v=data.data[j+3]>80?0:255;mask.data[j]=v;mask.data[j+1]=v;mask.data[j+2]=v;mask.data[j+3]=255;}const shape=await traceData(mask,2,false);const paths=[...shape.matchAll(/<path[^>]*fill="rgb\(0,0,0\)"[^>]*d="([^"]+)"/g)];return paths.map(p=>p[1]).join(' ');}

const pause=()=>new Promise<void>(r=>setTimeout(r,15));
export async function convert(source:string,layout:Layout,quads:Record<PanelId,Quad>,settings:Settings,onProgress:(n:number,label:string)=>void,only?:PanelId):Promise<{panels:Panel[];primary:string;secondary:string}>{
 onProgress(4,'Reading source image');const {data}=await imageToData(source,1900);const palette=estimatePalette(data),colors=chooseColors(palette);const panels:Panel[]=[];
 const ids=only?[only]:PANEL_IDS;
 for(let i=0;i<ids.length;i++){const id=ids[i],size=dimensions(id,settings);const factor=settings.detail/Math.max(size.w,size.h),h=Math.max(60,Math.round(size.h*factor)),w=Math.max(80,Math.round(size.w*factor));const missing=layout==='single'&&id==='back';onProgress(8+i*(82/ids.length),`Correcting ${NAMES[id].toLowerCase()}`);await pause();const cut=patternPath(id,w,h);
 if(missing){panels.push({id,name:NAMES[id],inner:`<path d="${cut}" fill="${colors.secondary}"/>`,width:w,height:h,cutPath:cut,sourceWidth:0,sourceHeight:0,missing:true,paths:1,palette});continue;}
 let warped=warp(data,quads[id],w,h);if(layout==='flat'&&settings.removeBackground)warped=removeOuterBackground(warped);if(layout!=='flat'){const c=canvas(w,h),ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.putImageData(warped,0,0);ctx.globalCompositeOperation='destination-in';ctx.fillStyle='black';ctx.fill(new Path2D(cut));warped=ctx.getImageData(0,0,w,h);}
 warped=cleanupData(warped,colors.primary,colors.secondary,settings.cleanup);const cc=canvas(w,h);cc.getContext('2d')!.putImageData(warped,0,0);const raster=cc.toDataURL('image/png');onProgress(14+i*(82/ids.length),`Tracing ${NAMES[id].toLowerCase()} into paths`);await pause();const inner=await traceData(warped,settings.cleanup==='flat'?3:settings.colors,true);const quad=quads[id];const sw=(Math.hypot((quad[1].x-quad[0].x)*data.width,(quad[1].y-quad[0].y)*data.height)+Math.hypot((quad[2].x-quad[3].x)*data.width,(quad[2].y-quad[3].y)*data.height))/2;const sh=(Math.hypot((quad[3].x-quad[0].x)*data.width,(quad[3].y-quad[0].y)*data.height)+Math.hypot((quad[2].x-quad[1].x)*data.width,(quad[2].y-quad[1].y)*data.height))/2;
 // The rectified flat sheet retains its own die silhouette; masks use the same outline.
 let cutPath=cut;if(layout==='flat'&&settings.removeBackground){const extracted=await extractCutPath(warped);if(extracted)cutPath=extracted;}
 const baseColor=baseFillColour(warped,colors.primary,colors.secondary);const base=`<path d="${cutPath}" fill="${baseColor}"/>`;
 panels.push({id,name:NAMES[id],inner:base+inner,width:w,height:h,cutPath,sourceWidth:Math.round(sw),sourceHeight:Math.round(sh),missing:false,paths:(inner.match(/<path/g)||[]).length,raster,palette});}
 onProgress(100,'Production panels prepared');return {panels,...colors};
}
let fontPromise:Promise<any>|undefined;
export async function getFont(){if(!fontPromise)fontPromise=Promise.all([fetch('/fonts/production-bold.ttf').then(r=>{if(!r.ok)throw new Error('The production font could not load.');return r.arrayBuffer();}),import('opentype.js')]).then(([b,m])=>(m.default || m).parse(b));return fontPromise;}
export function textPath(font:any,text:string,size:number,x:number,y:number,color:string){
 if(/[\u0980-\u09ff\u0600-\u06ff]/.test(text))throw new Error('For Bangla or Arabic lettering, upload the text as an image so it can be traced accurately.');
 const glyphs=[...text].map(c=>font.charToGlyph(c));if(glyphs.some((g:any)=>g.index===0))throw new Error('This text includes a character unavailable in the production font. Upload it as an image instead.');
 const factor=size/font.unitsPerEm;let advance=0;for(let i=0;i<glyphs.length;i++){advance+=(glyphs[i].advanceWidth||font.unitsPerEm*.5)*factor;if(i<glyphs.length-1)advance+=font.getKerningValue(glyphs[i],glyphs[i+1])*factor;}
 let at=x-advance/2;const paths:string[]=[];for(let i=0;i<glyphs.length;i++){paths.push(glyphs[i].getPath(at,y+size*.36,size).toPathData(2));at+=(glyphs[i].advanceWidth||font.unitsPerEm*.5)*factor;if(i<glyphs.length-1)at+=font.getKerningValue(glyphs[i],glyphs[i+1])*factor;}
 return `<path d="${paths.join(' ')}" fill="${color}"/>`;
}
export function overlayInner(o:Overlay,p:Panel,font?:any){const x=o.x/100*p.width,y=o.y/100*p.height,size=o.size/100*p.width;let inner='';if(o.type==='text')inner=font&&!/[\u0980-\u09ff\u0600-\u06ff]/.test(o.value)&&[...o.value].every(c=>font.charToGlyph(c).index!==0)?textPath(font,o.value,size,x,y,o.color):`<text x="${x}" y="${y}" dominant-baseline="middle" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="${size}" fill="${o.color}">${escapeXml(o.value)}</text>`;
 else if(o.svg){const w=size,h=size*(o.height||1)/(o.width||1);inner=`<g transform="translate(${x-w/2} ${y-h/2}) scale(${w/(o.width||1)} ${h/(o.height||1)})">${o.svg}</g>`;}
 return `<g transform="rotate(${o.rotation} ${x} ${y})">${inner}</g>`;
}
export function escapeXml(text:string){return text.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));}
export function panelInner(panel:Panel,overlays:Overlay[],font?:any,guides=false,bleed=3){const uid='clip_'+panel.id;return `<defs><clipPath id="${uid}"><path d="${panel.cutPath}"/></clipPath></defs><g clip-path="url(#${uid})">${panel.inner}${overlays.filter(o=>o.panel===panel.id).map(o=>overlayInner(o,panel,font)).join('')}</g>${guides?`<path d="${panel.cutPath}" fill="none" stroke="#00b9aa" stroke-width="1" stroke-dasharray="5 4"/>`:''}`;}
export function panelSvg(panel:Panel,project:Production,font?:any,guides=false){const {w,h}=dimensions(panel.id,project.settings),bleed=project.settings.bleed,px=bleed/w*panel.width,py=bleed/h*panel.height;return `<svg xmlns="http://www.w3.org/2000/svg" width="${w+bleed*2}mm" height="${h+bleed*2}mm" viewBox="${-px} ${-py} ${panel.width+2*px} ${panel.height+2*py}">${panelInner(panel,project.overlays,font,guides)}</svg>`;}
export function layoutMetrics(s:Settings){const gap=24+2*s.bleed,margin=20+s.bleed;const top=s.collarHeight+gap;const bodyY=margin+top;const sleeveY=bodyY+s.bodyHeight+gap;const width=Math.max(s.bodyWidth*2+gap,s.sleeveWidth*2+gap,s.collarWidth)+2*margin;const height=sleeveY+s.sleeveHeight+margin;const positions:Record<PanelId,Point>={front:{x:margin,y:bodyY},back:{x:margin+s.bodyWidth+gap,y:bodyY},leftSleeve:{x:margin+(s.bodyWidth-s.sleeveWidth)/2,y:sleeveY},rightSleeve:{x:margin+s.bodyWidth+gap+(s.bodyWidth-s.sleeveWidth)/2,y:sleeveY},collar:{x:(width-s.collarWidth)/2,y:margin}};return {width,height,positions};}
export function sheetSvg(project:Production,font?:any,guides=false){const {width,height,positions}=layoutMetrics(project.settings);const inner=project.panels.map(p=>{const size=dimensions(p.id,project.settings),pt=positions[p.id];return `<g id="${p.id}" transform="translate(${pt.x} ${pt.y}) scale(${size.w/p.width} ${size.h/p.height})">${panelInner(p,project.overlays,font,guides)}</g>`;}).join('');return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}"><title>${escapeXml(project.name)}</title><metadata>${escapeXml(JSON.stringify({units:'mm',settings:project.settings,pattern:'Reference-style polo, verify factory cutting template',reviewed:project.reviewed,confirmed:project.confirmed}))}</metadata>${inner}</svg>`;}
export function safeName(n:string){return n.replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,70)||'jersey-production';}
export function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export async function svgPng(svg:string,widthMM:number,heightMM:number,dpi:number){const w=Math.round(widthMM/25.4*dpi),h=Math.round(heightMM/25.4*dpi);if(w>16384||h>16384||w*h>65000000)throw new Error('This sheet is too large for a single PNG at this DPI. Export separate panels or lower the DPI.');const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const im=await loadImage(url),c=canvas(w,h);c.getContext('2d')!.drawImage(im,0,0,w,h);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNG export failed.')),'image/png'));return await addPngDpi(blob,dpi);}finally{URL.revokeObjectURL(url);}}
function crc32(bytes:Uint8Array){let crc=-1;for(const b of bytes){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^-1)>>>0;}
export async function addPngDpi(blob:Blob,dpi:number){const b=new Uint8Array(await blob.arrayBuffer());const chunk=new Uint8Array(21),dv=new DataView(chunk.buffer);dv.setUint32(0,9);chunk.set([112,72,89,115],4);const ppm=Math.round(dpi/0.0254);dv.setUint32(8,ppm);dv.setUint32(12,ppm);chunk[16]=1;dv.setUint32(17,crc32(chunk.subarray(4,17)));return new Blob([b.slice(0,33),chunk,b.slice(33)],{type:'image/png'});}
export async function svgPdf(svg:string,width:number,height:number){const [{jsPDF}]=await Promise.all([import('jspdf'),import('svg2pdf.js')]);const pdf=new jsPDF({orientation:width>height?'landscape':'portrait',unit:'mm',format:[width,height],compress:true});const parsed=new DOMParser().parseFromString(svg,'image/svg+xml');const svgEl=parsed.documentElement as unknown as SVGElement;await pdf.svg(svgEl,{x:0,y:0,width,height});return pdf.output('blob');}
export async function exportProduction(project:Production,format:'svg'|'pdf'|'png'|'zip'|'json',target:'sheet'|PanelId,guides=false){const name=safeName(project.name);if(format==='json'){const serial={schema:'my-jersey-studio/v1',...project,panels:project.panels.map(({raster,...p})=>p)};saveBlob(new Blob([JSON.stringify(serial)],{type:'application/json'}),name+'.jersey.json');return;}
 const font=await getFont();for(const o of project.overlays)if(o.type==='text')textPath(font,o.value,10,0,0,o.color);if(format==='zip'){const {default:JSZip}=await import('jszip');const zip=new JSZip();for(const p of project.panels){zip.file(`${name}-${p.id}.svg`,panelSvg(p,project,font,guides));}zip.file(`${name}-full-layout.svg`,sheetSvg(project,font,guides));const {width,height}=layoutMetrics(project.settings);zip.file(`${name}-full-layout.pdf`,await svgPdf(sheetSvg(project,font,guides),width,height));zip.file('production-specifications.json',JSON.stringify({units:'mm',settings:project.settings,panels:project.panels.map(p=>({id:p.id,size:dimensions(p.id,project.settings),sourceResolution:[p.sourceWidth,p.sourceHeight],missing:p.missing,paths:p.paths})),artworkReviewed:project.reviewed,patternConfirmed:project.confirmed,colorMode:'RGB; convert using your print shop ICC profile',bleed:'Border allocated; artwork is clipped at cut line. Extend artwork to bleed in your prepress application.',schema:'my-jersey-studio/v1'},null,2));zip.file('READ-ME.txt','My Jersey Studio production pack\nAll SVG/PDF dimensions are in millimetres. Text overlays are outlined.\nInspect fine text/logos, sleeve alignment and missing areas.\nUse your factory cutting template and printer ICC profile.\nBleed setting reserves border space; extend artwork to the bleed boundary before cutting.\nDo not scale the PDF when printing.\n');saveBlob(await zip.generateAsync({type:'blob'}),name+'-production-pack.zip');return;}
 const panel=project.panels.find(p=>p.id===target);if(target!=='sheet'&&!panel)throw new Error('Generate this panel first.');const svg=panel?panelSvg(panel,project,font,guides):sheetSvg(project,font,guides);const metrics=panel?dimensions(panel.id,project.settings):layoutMetrics(project.settings);const w='w'in metrics?metrics.w+project.settings.bleed*2:metrics.width,h='h'in metrics?metrics.h+project.settings.bleed*2:metrics.height;const suffix=target==='sheet'?'layout':target;
 if(format==='svg')saveBlob(new Blob([svg],{type:'image/svg+xml'}),`${name}-${suffix}.svg`);else if(format==='png')saveBlob(await svgPng(svg,w,h,project.settings.dpi),`${name}-${suffix}-${project.settings.dpi}dpi.png`);else saveBlob(await svgPdf(svg,w,h),`${name}-${suffix}.pdf`);
}
export async function traceLogo(url:string,removeBackground=true){const {data}=await imageToData(url,640);if(removeBackground)removeOuterBackground(data);return {svg:await traceData(data,16,true),width:data.width,height:data.height};}
export function preflight(project:Production){const all=project.panels.length===5;const missing=project.panels.filter(p=>p.missing);const raster=project.panels.some(p=>/<image\b/i.test(p.inner));const badText=project.overlays.some(o=>o.type==='text'&&/[\u0980-\u09ff\u0600-\u06ff]/.test(o.value));return [{title:'All five panels generated',ok:all,note:all?'Front, back, two sleeves and collar are present.':'Generate all five production pieces.'},{title:'Every panel is observed',ok:missing.length===0,note:missing.length?`Supply a ${missing.map(p=>p.name).join(', ')} image or review the blank panel.`:'Panels use artwork from the source.'},{title:'Vector artwork',ok:!raster,note:!raster?'Traced paths; added Latin text is outlined on export.':'Raster content remains in the design.'},{title:'Factory dimensions confirmed',ok:project.confirmed,note:'Confirm the dimensions and cut shape with your manufacturer.'},{title:'Artwork visually reviewed',ok:project.reviewed,note:'Inspect small logos, lettering and edges at 100%.'},{title:'Text can be outlined',ok:!badText,note:badText?'Use Latin text or upload non-Latin lettering as an image for tracing.':'All added text can be outlined with the bundled font.'}];}
export function applyQuickCommand(command:string,project:Production):{project:Production;message:string}{const s=command.trim(),low=s.toLowerCase();let next={...project,overlays:project.overlays.map(o=>({...o}))};let changes=0;const name=s.match(/(?:name|নাম)\s*(?:to|is|=|:|হবে)?\s*["']?([\p{L}][\p{L}\s.-]{0,34})/u);const number=s.match(/(?:number|নম্বর)\s*(?:to|is|=|:|হবে)?\s*(\d{1,3})/i);
 const put=(key:string,value:string,y:number,size:number)=>{const i=next.overlays.findIndex(o=>o.id===key);const o:Overlay={id:key,panel:'back',type:'text',value,x:50,y,size,rotation:0,color:next.primary};if(i>=0)next.overlays[i]={...next.overlays[i],value};else next.overlays.push(o);changes++;};
 if(name)put('player-name',name[1].trim().replace(/\s+(and|number|নম্বর).*$/i,''),24,10);if(number)put('player-number',number[1],48,34);
 const cmap:Record<string,string>={navy:'#10274e',blue:'#194dc8',black:'#151515',red:'#b41526',maroon:'#750b2c',green:'#14603b',gold:'#c19846',white:'#ffffff',cream:'#f4eddb'};
 for(const [word,hex]of Object.entries(cmap)){if(low.includes(word)){if(low.includes('base')||low.includes('background')){next.panels=replacePalette(next.panels,next.secondary,hex);next.secondary=hex;}else {next.panels=replacePalette(next.panels,next.primary,hex);next.overlays=next.overlays.map(o=>({...o,color:o.color===next.primary?hex:o.color}));next.primary=hex;}changes++;break;}}
 if(!changes)throw new Error('Quick commands support name, number and colour changes. For other requests, connect an AI provider or use the editor.');next.reviewed=false;return {project:next,message:`Applied ${changes} edit${changes===1?'':'s'}. Existing lettering in the photograph remains part of the artwork.`};}
export function replacePalette(panels:Panel[],from:string,to:string){return panels.map(p=>({...p,inner:p.inner.replace(/rgb\((\d+),(\d+),(\d+)\)/g,(full,r,g,b)=>{const col='#'+[r,g,b].map(v=>Number(v).toString(16).padStart(2,'0')).join('');return colorDistance(col,from)<70?to:full;}).split(from).join(to)}));}
export function validateProject(value:unknown):Production{const p=value as Production&{schema:string};if(!p||p.schema!=='my-jersey-studio/v1'||!Array.isArray(p.panels)||p.panels.length>5||!Array.isArray(p.overlays)||p.overlays.length>100||!p.settings)throw new Error('This is not a valid My Jersey Studio project.');for(const panel of p.panels){if(!PANEL_IDS.includes(panel.id)||typeof panel.inner!=='string'||/<\s*(script|foreignObject|image|iframe|style)|\bon\w+\s*=|href\s*=|url\(\s*(?!#)/i.test(panel.inner))throw new Error('The project contains unsupported content.');if(!Number.isFinite(panel.width)||!Number.isFinite(panel.height)||panel.width<=0||panel.height<=0)throw new Error('Invalid panel size.');if(typeof panel.cutPath!=='string'||!/^[MmLlHhVvCcSsQqTtAaZz0-9.,\s+eE-]+$/.test(panel.cutPath))throw new Error('Invalid cut path.');}for(const o of p.overlays){if(!PANEL_IDS.includes(o.panel)||!['text','logo'].includes(o.type)||typeof o.value!=='string'||(o.svg&&/<\s*(script|foreignObject|image|iframe|style)|\bon\w+\s*=|href\s*=|url\(\s*(?!#)/i.test(o.svg)))throw new Error('Invalid design layer.');if(!/^#[0-9a-f]{6}$/i.test(o.color))throw new Error('Invalid layer colour.');for(const n of [o.x,o.y,o.size,o.rotation])if(!Number.isFinite(n))throw new Error('Invalid layer position.');}for(const [k,v]of Object.entries(DEFAULT_SETTINGS)){const x=p.settings[k as keyof Settings];if(typeof x!==typeof v||(typeof x==='number'&&(!Number.isFinite(x)||x<0||x>5000)))throw new Error('Invalid production settings.');}p.reviewed=false;p.confirmed=false;return p;}
