import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {PANEL_IDS,NAMES,DEFAULT_SETTINGS,defaultQuads,dimensions,patternPath,homography,validateQuad,warp,removeOuterBackground,cleanupData,traceData,estimatePalette,chooseColors,sheetSvg,panelSvg,layoutMetrics,textPath,preflight,applyQuickCommand,validateProject,addPngDpi,extractCutPath,baseFillColour} from '../lib/production';
import type {Panel,Production} from '../lib/production';
import * as opentype from 'opentype.js';
const require=createRequire(import.meta.url);const sharp=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/sharp');
class TestImageData{width:number;height:number;data:Uint8ClampedArray;constructor(w:number,h:number){this.width=w;this.height=h;this.data=new Uint8ClampedArray(w*h*4);}}
(globalThis as any).ImageData=TestImageData;
for(const type of ['flat','pair','single'] as const)for(const id of PANEL_IDS)validateQuad(defaultQuads(type)[id]);
const skew=[{x:.1,y:.2},{x:.9,y:.1},{x:.8,y:.8},{x:.2,y:.9}] as any;
const m=homography(skew);for(const [u,v,index] of [[0,0,0],[1,0,1],[1,1,2],[0,1,3]]){const z=m.g*u+m.h*v+1;assert(Math.abs((m.a*u+m.b*v+m.c)/z-skew[index].x)<1e-9);assert(Math.abs((m.d*u+m.e*v+m.f)/z-skew[index].y)<1e-9);}
assert.throws(()=>validateQuad([{x:0,y:0},{x:1,y:1},{x:1,y:0},{x:0,y:1}] as any));
// Edge removal must retain cream artwork enclosed inside a garment.
const bg=new TestImageData(10,10);for(let i=0;i<bg.data.length;i+=4)bg.data.set([255,255,255,255],i);for(let y=2;y<8;y++)for(let x=2;x<8;x++)bg.data.set(x===2||x===7||y===2||y===7?[120,10,40,255]:[245,239,225,255],(y*10+x)*4);removeOuterBackground(bg as any);assert.equal(bg.data[3],0);assert.equal(bg.data[(5*10+5)*4+3],255);
const fontBuffer=readFileSync('public/fonts/production-bold.ttf');const font=(opentype.default || opentype).parse(fontBuffer.buffer.slice(fontBuffer.byteOffset,fontBuffer.byteOffset+fontBuffer.byteLength));assert(!textPath(font,'NAHID 10',40,200,150,'#123456').includes('<text'));
const outputRoot=process.env.JERSEY_VERIFY_OUTPUT||'.sites-runtime/validation';mkdirSync(outputRoot,{recursive:true});const reports:any[]=[];
for(const layout of ['flat','pair'] as const){const path=layout==='flat'?'public/examples/production-reference.jpg':'public/examples/jersey-photo.jpg';const {data:bytes,info}=await sharp(path).ensureAlpha().raw().toBuffer({resolveWithObject:true});const source={data:new Uint8ClampedArray(bytes),width:info.width,height:info.height} as ImageData;const palette=estimatePalette(source),col=chooseColors(palette),panels:Panel[]=[];
 for(const id of PANEL_IDS){const s=dimensions(id,DEFAULT_SETTINGS),factor=480/Math.max(s.w,s.h),h=Math.max(60,Math.round(s.h*factor)),w=Math.max(80,Math.round(s.w*factor)),q=defaultQuads(layout)[id];let data=warp(source,q,w,h);if(layout==='flat')removeOuterBackground(data);cleanupData(data,col.primary,col.secondary,'preserve');let inner=await traceData(data,16,true),cut=patternPath(id,w,h);
 if(layout==='flat'){const extracted=await extractCutPath(data);assert(extracted.length>20,'Reference silhouette must exist');cut=extracted;}inner=`<path d="${cut}" fill="${baseFillColour(data,col.primary,col.secondary)}"/>`+inner;
 assert(!/<image|<script/.test(inner));assert((inner.match(/<path/g)||[]).length>4,'Real source must produce detailed paths');panels.push({id,name:NAMES[id],inner,width:w,height:h,cutPath:cut,sourceWidth:info.width,sourceHeight:info.height,missing:false,paths:(inner.match(/<path/g)||[]).length,palette});}
 const project:Production={panels,settings:{...DEFAULT_SETTINGS},overlays:[],...col,name:'Verified '+layout,source:path,sourceName:path,layout,quads:defaultQuads(layout),reviewed:false,confirmed:false};const svg=sheetSvg(project,font,false);const metrics=layoutMetrics(project.settings);assert(svg.includes(`width="${metrics.width}mm"`));assert(!svg.includes('<image'));assert(!svg.includes('<text'));const p=panelSvg(panels[0],project,font);assert(p.includes('width="566mm"'));assert(p.includes('height="746mm"'));writeFileSync(outputRoot+'/'+layout+'-layout.svg',svg);await sharp(Buffer.from(svg)).resize({width:900}).png().toFile(outputRoot+'/'+layout+'-layout.png');
 const edit=applyQuickCommand('Change name to NAHID and number to 10',project);assert.equal(edit.project.overlays.find(o=>o.id==='player-name')?.value,'NAHID');assert.equal(edit.project.overlays.find(o=>o.id==='player-number')?.value,'10');const outlined=sheetSvg(edit.project,font);assert(!outlined.includes('<text'));assert.throws(()=>applyQuickCommand('Please invent an unseen illustration',project));assert.equal(preflight(project).filter(c=>!c.ok).length,2);validateProject({schema:'my-jersey-studio/v1',...project});assert.throws(()=>validateProject({schema:'my-jersey-studio/v1',...project,panels:[{...panels[0],inner:'<script>alert(1)</script>'}]}));
 reports.push({layout,totalPaths:panels.reduce((n,p)=>n+p.paths,0),sheetMM:[metrics.width,metrics.height],panels:panels.map(p=>({id:p.id,paths:p.paths})),palette});}
const testPng=await sharp({create:{width:10,height:10,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).png().toBuffer();const dpi=await addPngDpi(new Blob([testPng]),300);const bytes=new Uint8Array(await dpi.arrayBuffer());assert.equal(String.fromCharCode(...bytes.slice(37,41)),'pHYs');assert.equal(new DataView(bytes.buffer).getUint32(41),11811);
console.log(JSON.stringify({status:'passed',checks:['four-corner homography','invalid geometry rejection','background removal retains enclosed artwork','five reference silhouettes','photograph tracing','no embedded raster in exports','outlined text','true millimetre sizing','local name and number commands','project validation and script rejection','PNG 300 DPI metadata'],reports},null,2));
